apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-router
  labels:
    {{- include "hypixel.labels" (dict "root" . "component" "router") | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-router
  replicas: {{ .Values.replicas.router }}
  selector:
    matchLabels:
      {{- include "hypixel.selectorLabels" (dict "root" . "component" "router") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hypixel.labels" (dict "root" . "component" "router") | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        runAsGroup: 65532
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: router
          image: {{ index .Values.images "cf-router" }}
          env:
            - name: FORWARDS
              value: "0.0.0.0:{{ .Values.ports.router }}={{ .Values.config.router.server_endpoint }}"
            {{- include "hypixel.extraEnv" (dict "root" . "component" "router") | nindent 12 }}
          {{- include "hypixel.extraEnvFrom" (dict "root" . "component" "router") | nindent 10 }}
          ports:
            - name: minecraft
              containerPort: {{ .Values.ports.router }}
          resources:
            {{- toYaml .Values.resources.router | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "hypixel.labels" (dict "root" . "component" "router") | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-router
  labels:
    {{- include "hypixel.labels" (dict "root" . "component" "router") | nindent 4 }}
spec:
  selector:
    {{- include "hypixel.selectorLabels" (dict "root" . "component" "router") | nindent 4 }}
  ports:
    - port: {{ .Values.ports.router }}
      targetPort: minecraft
