apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-valkey
  labels:
    {{- include "hypixel.labels" (dict "root" . "component" "valkey") | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.valkey }}
  selector:
    matchLabels:
      {{- include "hypixel.selectorLabels" (dict "root" . "component" "valkey") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hypixel.labels" (dict "root" . "component" "valkey") | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: valkey
          image: {{ .Values.images.valkey }}
          {{- with (index .Values.extraEnv "valkey") }}
          env:
            {{- include "hypixel.extraEnv" (dict "root" $ "component" "valkey") | nindent 12 }}
          {{- end }}
          {{- include "hypixel.extraEnvFrom" (dict "root" . "component" "valkey") | nindent 10 }}
          args:
            - --protected-mode
            - "no"
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - name: valkey
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: valkey
          livenessProbe:
            tcpSocket:
              port: valkey
          resources:
            {{- toYaml .Values.resources.valkey | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-valkey
  labels:
    {{- include "hypixel.labels" (dict "root" . "component" "valkey") | nindent 4 }}
spec:
  selector:
    {{- include "hypixel.selectorLabels" (dict "root" . "component" "valkey") | nindent 4 }}
  ports:
    - port: {{ .Values.ports.valkey }}
      targetPort: valkey
