images:
  compatlink: ghcr.io/guild-link/compatlink@sha256:f33c79ffa381916283fac805ffec7ad47a8de67b9e3432404215542955a34764
  hypixel-grpc: ""
ports:
  hypixel-grpc: 50051
  compatlink: 80
replicas:
  hypixel-grpc: 1
  compatlink: 1
resources:
  hypixel-grpc:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  compatlink:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
