images:
  guildlink: ghcr.io/guild-link/guildlink@sha256:b5d41e4527dbc6293108fdc246c73a17cf2967be26336ded51ac4a8d5ede5b2b
  worker-rs: ghcr.io/guild-link/worker-rs@sha256:573d3cf7cf6074059ed223fbfc2af6dca6e53327c9cee2bc62b6d309e7203310
  valkey: valkey/valkey:latest
ports:
  valkey: 6379
config:
  bot:
    hypixel_endpoint: ""
    public_key: ""
  worker:
    address: mc.hypixel.net
    hostname: null
extraEnv:
  worker: []
  valkey: []
  bot: []
extraEnvFrom:
  worker: []
  valkey: []
  bot: []
replicas:
  worker: 1
  valkey: 1
  bot: 1
resources:
  bot:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  worker:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  valkey:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1024Mi
