images:
  guildlink: ghcr.io/guild-link/guildlink@sha256:b5d41e4527dbc6293108fdc246c73a17cf2967be26336ded51ac4a8d5ede5b2b
  worker-rs: ghcr.io/guild-link/worker-rs@sha256:b4424c51ee29f119d6b92e26a8b363057921fcf2c36c9acf0412f19e21dff7d4
  valkey: valkey/valkey:latest
config:
  bot:
    mc_auth_endpoint: "https://mc-auth.chickeniq.net"
    hypixel_endpoint: ""
    mc_auth_sigkey: "M5qAL6Bi4XPgHuYVcUe9No0witldOPEbCRmzEZn7Fdg="
    mc_auth_enckey: ""
  worker:
    hostname: mc.hypixel.net
    address: mc.hypixel.net
extraEnv:
  worker: []
  valkey: []
  bot: []
extraEnvFrom:
  worker: []
  valkey: []
  bot: []
replicas:
  worker: 1
  bot: 1
resources:
  worker:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 128Mi
  bot:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
  valkey:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
