images:
  hypixel-grpc: ghcr.io/guild-link/hypixel-grpc@sha256:b117c5d246f99a0916203545afc4c89a6a7f53bf1442c96c0cb80d560acee657
  compatlink: ghcr.io/guild-link/compatlink@sha256:2e02b71aa4f3781f1053e1f6580d49d8d146b23594e2c0777ddd4076cd381178
  cf-router: ghcr.io/guild-link/cf-router@sha256:f5b96751b2a9a3a84df83afac390cb501c8be42cc9b48d6af3d77e4023c81297
  valkey: valkey/valkey:latest
ports:
  compat-api: 80
  router: 25565
  valkey: 6379
  api: 50051
config:
  router:
    server_endpoint: mc.hypixel.net:25565
extraEnv:
  api: []
  compat-api: []
  router: []
  valkey: []
extraEnvFrom:
  compat-api: []
  router: []
  valkey: []
  api: []
replicas:
  compat-api: 1
  router: 1
  valkey: 1
  api: 1
resources:
  api:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  compat-api:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  router:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      memory: 64Mi
  valkey:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
